# -*- coding: utf-8 -*-
"""Feature map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1On9aCZYLl5zP4dYcu1UYZTS2IfI7QMjS
"""

from tensorflow.keras.models import load_model
model = load_model('my_model1.h5')
model.summary()

pip install tf-hub-nightly

from tensorflow.keras.models import Model
layer_dict = dict([(layer.name, layer) for layer in model.layers])

layer_name = 'conv2d_1'
model = Model(inputs=model.inputs, outputs=layer_dict[layer_name].output)

import numpy as np
from keras.applications.imagenet_utils import preprocess_input
from tensorflow.keras.preprocessing.image import load_img,img_to_array

image = load_img('O.PNG', target_size=(64, 64))
image = img_to_array(image)
image = np.expand_dims(image, axis=0)
image = preprocess_input(image)

feature_maps = model.predict(image)

import matplotlib.pyplot as plt
square = 8
index = 1
for _ in range(square):
	for _ in range(square):
        
		ax = plt.subplot(square, square, index)
		ax.set_xticks([])
		ax.set_yticks([])

		plt.imshow(feature_maps[0, :, :, index-1], cmap='viridis')
		index += 1
        
plt.show()